"""Update payload to Text from string

Revision ID: 90ec60294854
Revises: fdc21233f70e
Create Date: 2023-06-03 10:33:33.623029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ec60294854'
down_revision = 'fdc21233f70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chats', schema=None) as batch_op:
        batch_op.alter_column('chatPayload',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chats', schema=None) as batch_op:
        batch_op.alter_column('chatPayload',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
